.TH "gthumb" "1" "0.5" "Remco van de Meent" ""
.SH "НАЗВАНИЕ"
.LP 
gthumb \- просмотрщик и навигатор изображений для GNOME
.SH "СИНТАКСИС"  
.LP 
gthumb [\fI<каталог>\fP]
.br 
gthumb [\fI<имя файла>\fP]
.SH "ОПИСАНИЕ"
.LP 
С помощью gthumb возможен поиск каталогов содержащих картинки или фотографии, а так же их просмотр. Кроме того получить данные о файлах,содержащих эти изображения.
.SH "ПАРАМЕТРЫ"
.LP 
.TP 
\fB<\fIкаталог\fP>
Просмотр изображений в заданном каталоге <\fIкаталог\fP>.
.TP 
\fB<\fIимя файла\fP>
Просмотр изображения с заданным именем <\fIимя файла\fP>.
.TP 
\fB\-\-help\fR
Вывод на экран справочной информации.
.TP 
\fB\-\-version\fR
Вывод на экран номера версии программы.
.TP 
Другие параметры GNOME так же применимы.
.SH "ПРИМЕРЫ"
.LP 
Стандартный запуск программы:
.LP 
gthumb /home/yourname/pix
.LP
gthumb /home/yourname/*.jpg
.SH "АВТОРЫ"
.LP 
Эта страница руководства написана Remco van de Meent <remco@debian.org>, для системы Debian GNU/Linux (но может быть использована и для других систем).


