/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif /* __STDC__ */
#endif /* ! __cplusplus */

#ifdef __TURBOC__
#pragma warn -rch
#pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
{
  FILE *yy_input_file;

  char *yy_ch_buf;		/* input buffer */
  char *yy_buf_pos;		/* current position in input buffer */

  /* Size of input buffer in bytes, not including room for EOB
   * characters.
   */
  yy_size_t yy_buf_size;

  /* Number of characters read into yy_ch_buf, not including EOB
   * characters.
   */
  int yy_n_chars;

  /* Whether we "own" the buffer - i.e., we know we created it,
   * and can realloc() it to grow it, and should free() it to
   * delete it.
   */
  int yy_is_our_buffer;

  /* Whether this is an "interactive" input source; if so, and
   * if we're using stdio for input, then we want to use getc()
   * instead of fread(), to make sure we stop fetching input after
   * each newline.
   */
  int yy_is_interactive;

  /* Whether we're considered to be at the beginning of a line.
   * If so, '^' rules will be active on the next match, otherwise
   * not.
   */
  int yy_at_bol;

  /* Whether to try to fill the input buffer when we reach the
   * end of it.
   */
  int yy_fill_buffer;

  int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
  /* When an EOF's been seen but there's still some text to process
   * then we mark the buffer as YY_EOF_PENDING, to indicate that we
   * shouldn't try reading from the input source any more.  We might
   * still have a bunch of tokens to match, though, because of
   * possible backing-up.
   *
   * When we actually see the EOF, we change the status to "new"
   * (via yyrestart()), so that the user can continue scanning by
   * just pointing yyin at a new input file.
   */
#define YY_BUFFER_EOF_PENDING 2
};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO ((FILE * input_file));

void yy_switch_to_buffer YY_PROTO ((YY_BUFFER_STATE new_buffer));
void yy_load_buffer_state YY_PROTO ((void));
YY_BUFFER_STATE yy_create_buffer YY_PROTO ((FILE * file, int size));
void yy_delete_buffer YY_PROTO ((YY_BUFFER_STATE b));
void yy_init_buffer YY_PROTO ((YY_BUFFER_STATE b, FILE * file));
void yy_flush_buffer YY_PROTO ((YY_BUFFER_STATE b));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO ((char *base, yy_size_t size));
YY_BUFFER_STATE yy_scan_string YY_PROTO ((yyconst char *yy_str));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO ((yyconst char *bytes, int len));

static void *yy_flex_alloc YY_PROTO ((yy_size_t));
static void *yy_flex_realloc YY_PROTO ((void *, yy_size_t));
static void yy_flex_free YY_PROTO ((void *));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO ((void));
static yy_state_type yy_try_NUL_trans
YY_PROTO ((yy_state_type current_state));
static int yy_get_next_buffer YY_PROTO ((void));
static void yy_fatal_error YY_PROTO ((yyconst char msg[]));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
static yyconst short int yy_accept[224] = { 0,
  0, 0, 0, 0, 43, 41, 40, 42, 38, 28,
  31, 42, 29, 30, 26, 27, 42, 21, 24, 23,
  25, 22, 42, 41, 0, 35, 32, 39, 21, 36,
  34, 37, 22, 33, 41, 0, 41, 0, 41, 0,
  41, 0, 41, 0, 41, 0, 41, 0, 0, 0,
  0, 0, 0, 0, 0, 41, 0, 0, 0, 0,
  0, 17, 0, 0, 0, 0, 0, 41, 0, 0,
  0, 20, 0, 0, 0, 0, 0, 0, 41, 0,
  15, 18, 0, 0, 0, 0, 0, 0, 41, 0,
  0, 0, 2, 0, 13, 0, 14, 1, 41, 0,

  0, 0, 0, 0, 0, 6, 0, 0, 0, 41,
  10, 19, 0, 0, 0, 0, 0, 0, 0, 0,
  16, 41, 0, 0, 0, 0, 0, 0, 12, 0,
  41, 7, 8, 9, 5, 4, 0, 11, 41, 3,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,

  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
  41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
  41, 41, 0
};

static yyconst int yy_ec[256] = { 0,
  1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 2, 3, 4, 1, 1, 1, 5, 1, 6,
  7, 1, 8, 1, 9, 1, 10, 11, 11, 11,
  11, 11, 11, 11, 11, 11, 11, 12, 1, 13,
  14, 15, 1, 1, 16, 16, 16, 16, 16, 16,
  16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
  16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
  1, 1, 1, 1, 17, 1, 18, 19, 20, 21,

  22, 23, 24, 25, 26, 16, 27, 28, 29, 30,
  31, 32, 16, 33, 34, 35, 36, 37, 16, 38,
  16, 39, 1, 40, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1
};

static yyconst int yy_meta[41] = { 0,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 2, 1, 1, 3, 3, 3, 3, 3,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 1
};

static yyconst short int yy_base[326] = { 0,
  223, 220, 0, 40, 230, 0, 203, 400, 400, 210,
  400, 216, 400, 400, 400, 400, 203, 204, 198, 195,
  192, 0, 163, 0, 165, 400, 400, 400, 186, 400,
  400, 400, 0, 400, 0, 169, 0, 155, 0, 159,
  0, 166, 0, 170, 0, 61, 0, 148, 158, 0,
  147, 0, 152, 145, 0, 0, 135, 126, 124, 134,
  124, 400, 131, 122, 108, 121, 102, 0, 105, 109,
  106, 400, 103, 98, 97, 99, 85, 82, 0, 85,
  400, 87, 77, 70, 0, 54, 68, 67, 0, 58,
  60, 1, 2, 11, 400, 67, 400, 400, 0, 44,

  55, 59, 58, 49, 35, 400, 53, 47, 39, 0,
  400, 400, 42, 35, 30, 42, 46, 40, 27, 34,
  400, 0, 40, 35, 37, 29, 19, 8, 400, 5,
  0, 400, 400, 400, 400, 400, 0, 400, 0, 400,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 400, 400, 96, 99, 102, 13, 105, 108, 111,
  114, 117, 120, 123, 126, 129, 132, 135, 138, 141,
  144, 147, 150, 153, 156, 159, 162, 165, 168, 171,
  174, 177, 180, 183, 186, 189, 192, 195, 198, 201,
  204, 207, 210, 213, 216, 219, 222, 225, 228, 231,
  234, 237, 240, 243, 246, 249, 252, 255, 258, 261,
  264, 267, 270, 273, 276, 279, 282, 285, 288, 291,
  294, 297, 300, 303, 306, 309, 312, 315, 318, 321,

  324, 327, 330, 333, 336, 339, 342, 345, 348, 351,
  354, 357, 360, 363, 366, 369, 372, 375, 378, 381,
  384, 387, 390, 393, 396
};

static yyconst short int yy_def[326] = { 0,
  224, 224, 225, 225, 223, 226, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 227, 223, 228, 223, 223, 223, 223, 223, 223,
  223, 223, 227, 223, 229, 223, 230, 223, 231, 223,
  232, 223, 233, 223, 234, 223, 235, 223, 223, 223,
  223, 223, 223, 223, 223, 236, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 237, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 238, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 239, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 240, 223,

  223, 223, 223, 223, 223, 223, 223, 223, 223, 241,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 242, 223, 223, 223, 223, 223, 223, 223, 223,
  243, 223, 223, 223, 223, 223, 223, 223, 244, 223,
  245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
  255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
  265, 266, 267, 268, 269, 270, 271, 272, 273, 274,
  275, 276, 277, 278, 279, 280, 281, 282, 283, 284,
  285, 286, 287, 288, 289, 290, 291, 292, 293, 294,
  295, 296, 297, 298, 299, 300, 301, 302, 303, 304,

  305, 306, 307, 308, 309, 310, 311, 312, 313, 314,
  315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
  325, 223, 0, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,

  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223
};

static yyconst short int yy_nxt[441] = { 0,
  8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
  18, 8, 19, 20, 21, 33, 94, 66, 105, 223,
  223, 223, 62, 223, 223, 67, 140, 59, 63, 60,
  102, 138, 103, 95, 104, 106, 107, 137, 108, 23,
  8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
  18, 8, 19, 20, 21, 116, 136, 135, 134, 133,
  117, 132, 118, 130, 129, 128, 127, 126, 125, 124,
  123, 121, 120, 119, 115, 114, 113, 112, 111, 23,
  48, 49, 50, 51, 109, 101, 52, 100, 98, 97,
  96, 93, 53, 92, 54, 55, 6, 6, 6, 22,

  22, 22, 24, 91, 24, 35, 90, 35, 37, 88,
  37, 39, 87, 39, 41, 86, 41, 43, 85, 43,
  45, 84, 45, 47, 83, 47, 56, 82, 56, 68,
  81, 68, 79, 80, 79, 89, 78, 89, 99, 77,
  99, 110, 76, 110, 122, 75, 122, 131, 74, 131,
  139, 73, 139, 141, 72, 141, 142, 71, 142, 143,
  70, 143, 144, 69, 144, 145, 65, 145, 146, 64,
  146, 147, 61, 147, 148, 58, 148, 149, 57, 149,
  150, 46, 150, 151, 44, 151, 152, 42, 152, 153,
  40, 153, 154, 38, 154, 155, 29, 155, 156, 36,

  156, 157, 34, 157, 158, 32, 158, 159, 31, 159,
  160, 30, 160, 161, 29, 161, 162, 28, 162, 163,
  27, 163, 164, 26, 164, 165, 25, 165, 166, 223,
  166, 167, 7, 167, 168, 7, 168, 169, 223, 169,
  170, 223, 170, 171, 223, 171, 172, 223, 172, 173,
  223, 173, 174, 223, 174, 175, 223, 175, 176, 223,
  176, 177, 223, 177, 178, 223, 178, 179, 223, 179,
  180, 223, 180, 181, 223, 181, 182, 223, 182, 183,
  223, 183, 184, 223, 184, 185, 223, 185, 186, 223,
  186, 187, 223, 187, 188, 223, 188, 189, 223, 189,

  190, 223, 190, 191, 223, 191, 192, 223, 192, 193,
  223, 193, 194, 223, 194, 195, 223, 195, 196, 223,
  196, 197, 223, 197, 198, 223, 198, 199, 223, 199,
  200, 223, 200, 201, 223, 201, 202, 223, 202, 203,
  223, 203, 204, 223, 204, 205, 223, 205, 206, 223,
  206, 207, 223, 207, 208, 223, 208, 209, 223, 209,
  210, 223, 210, 211, 223, 211, 212, 223, 212, 213,
  223, 213, 214, 223, 214, 215, 223, 215, 216, 223,
  216, 217, 223, 217, 218, 223, 218, 219, 223, 219,
  220, 223, 220, 221, 223, 221, 222, 223, 222, 5,

  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223
};

static yyconst short int yy_chk[441] = { 0,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  3, 3, 3, 3, 3, 227, 85, 55, 93, 0,
  0, 0, 52, 0, 0, 55, 137, 50, 52, 50,
  92, 130, 92, 85, 92, 93, 94, 128, 94, 3,
  4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
  4, 4, 4, 4, 4, 105, 127, 126, 125, 124,
  105, 123, 105, 120, 119, 118, 117, 116, 115, 114,
  113, 109, 108, 107, 104, 103, 102, 101, 100, 4,
  46, 46, 46, 46, 96, 91, 46, 90, 88, 87,
  86, 84, 46, 83, 46, 46, 224, 224, 224, 225,

  225, 225, 226, 82, 226, 228, 80, 228, 229, 78,
  229, 230, 77, 230, 231, 76, 231, 232, 75, 232,
  233, 74, 233, 234, 73, 234, 235, 71, 235, 236,
  70, 236, 237, 69, 237, 238, 67, 238, 239, 66,
  239, 240, 65, 240, 241, 64, 241, 242, 63, 242,
  243, 61, 243, 244, 60, 244, 245, 59, 245, 246,
  58, 246, 247, 57, 247, 248, 54, 248, 249, 53,
  249, 250, 51, 250, 251, 49, 251, 252, 48, 252,
  253, 44, 253, 254, 42, 254, 255, 40, 255, 256,
  38, 256, 257, 36, 257, 258, 29, 258, 259, 25,

  259, 260, 23, 260, 261, 21, 261, 262, 20, 262,
  263, 19, 263, 264, 18, 264, 265, 17, 265, 266,
  12, 266, 267, 10, 267, 268, 7, 268, 269, 5,
  269, 270, 2, 270, 271, 1, 271, 272, 0, 272,
  273, 0, 273, 274, 0, 274, 275, 0, 275, 276,
  0, 276, 277, 0, 277, 278, 0, 278, 279, 0,
  279, 280, 0, 280, 281, 0, 281, 282, 0, 282,
  283, 0, 283, 284, 0, 284, 285, 0, 285, 286,
  0, 286, 287, 0, 287, 288, 0, 288, 289, 0,
  289, 290, 0, 290, 291, 0, 291, 292, 0, 292,

  293, 0, 293, 294, 0, 294, 295, 0, 295, 296,
  0, 296, 297, 0, 297, 298, 0, 298, 299, 0,
  299, 300, 0, 300, 301, 0, 301, 302, 0, 302,
  303, 0, 303, 304, 0, 304, 305, 0, 305, 306,
  0, 306, 307, 0, 307, 308, 0, 308, 309, 0,
  309, 310, 0, 310, 311, 0, 311, 312, 0, 312,
  313, 0, 313, 314, 0, 314, 315, 0, 315, 316,
  0, 316, 317, 0, 317, 318, 0, 318, 319, 0,
  319, 320, 0, 320, 321, 0, 321, 322, 0, 322,
  323, 0, 323, 324, 0, 324, 325, 0, 325, 223,

  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223,
  223, 223, 223, 223, 223, 223, 223, 223, 223, 223
};

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "albumtheme.l"
#define INITIAL 0
#line 2 "albumtheme.l"
/*
 *  GThumb
 *
 *  Copyright (C) 2003 Free Software Foundation, Inc.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Street #330, Boston, MA 02111-1307, USA.
 */

#include <glib.h>

#define TAG 1

#line 579 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO ((void));
#else
extern int yywrap YY_PROTO ((void));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO ((int c, char *buf_ptr));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO ((char *, yyconst char *, int));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO ((yyconst char *));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO ((void));
#else
static int input YY_PROTO ((void));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO ((int new_state));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO ((void));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO ((void));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
{
  register yy_state_type yy_current_state;
  register char *yy_cp = NULL, *yy_bp = NULL;
  register int yy_act;

#line 31 "albumtheme.l"


#line 733 "lex.yy.c"

  if (yy_init)
    {
      yy_init = 0;

#ifdef YY_USER_INIT
      YY_USER_INIT;
#endif

      if (!yy_start)
	yy_start = 1;		/* first start state */

      if (!yyin)
	yyin = stdin;

      if (!yyout)
	yyout = stdout;

      if (!yy_current_buffer)
	yy_current_buffer = yy_create_buffer (yyin, YY_BUF_SIZE);

      yy_load_buffer_state ();
    }

  while (1)			/* loops until end-of-file is reached */
    {
      yy_cp = yy_c_buf_p;

      /* Support of yytext. */
      *yy_cp = yy_hold_char;

      /* yy_bp points to the position in yy_ch_buf of the start of
       * the current run.
       */
      yy_bp = yy_cp;

      yy_current_state = yy_start;
    yy_match:
      do
	{
	  register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI (*yy_cp)];
	  if (yy_accept[yy_current_state])
	    {
	      yy_last_accepting_state = yy_current_state;
	      yy_last_accepting_cpos = yy_cp;
	    }
	  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	    {
	      yy_current_state = (int) yy_def[yy_current_state];
	      if (yy_current_state >= 224)
		yy_c = yy_meta[(unsigned int) yy_c];
	    }
	  yy_current_state =
	    yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	  ++yy_cp;
	}
      while (yy_base[yy_current_state] != 400);

    yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if (yy_act == 0)
	{			/* have to back up */
	  yy_cp = yy_last_accepting_cpos;
	  yy_current_state = yy_last_accepting_state;
	  yy_act = yy_accept[yy_current_state];
	}

      YY_DO_BEFORE_ACTION;


    do_action:			/* This label is used only to access EOF actions. */


      switch (yy_act)
	{			/* beginning of action switch */
	case 0:		/* must back up */
	  /* undo the effects of YY_DO_BEFORE_ACTION */
	  *yy_cp = yy_hold_char;
	  yy_cp = yy_last_accepting_cpos;
	  yy_current_state = yy_last_accepting_state;
	  goto yy_find_action;

	case 1:
	  YY_RULE_SETUP
#line 33 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_TITLE;
	    return TITLE;
	  }
	YY_BREAK case 2:
	  YY_RULE_SETUP
#line 38 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE;
	    return IMAGE;
	  }
	YY_BREAK case 3:
	  YY_RULE_SETUP
#line 43 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE_LINK;
	    return IMAGE_LINK;
	  }
	YY_BREAK case 4:
	  YY_RULE_SETUP
#line 48 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE_IDX;
	    return IMAGE_IDX;
	  }
	YY_BREAK case 5:
	  YY_RULE_SETUP
#line 53 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE_DIM;
	    return IMAGE_DIM;
	  }
	YY_BREAK case 6:
	  YY_RULE_SETUP
#line 58 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGES;
	    return IMAGES;
	  }
	YY_BREAK case 7:
	  YY_RULE_SETUP
#line 63 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_FILENAME;
	    return FILENAME;
	  }
	YY_BREAK case 8:
	  YY_RULE_SETUP
#line 68 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_FILEPATH;
	    return FILEPATH;
	  }
	YY_BREAK case 9:
	  YY_RULE_SETUP
#line 73 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_FILESIZE;
	    return FILESIZE;
	  }
	YY_BREAK case 10:
	  YY_RULE_SETUP
#line 78 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_COMMENT;
	    return COMMENT;
	  }
	YY_BREAK case 11:
	  YY_RULE_SETUP
#line 83 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_PAGE_LINK;
	    return PAGE_LINK;
	  }
	YY_BREAK case 12:
	  YY_RULE_SETUP
#line 88 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_PAGE_IDX;
	    return PAGE_IDX;
	  }
	YY_BREAK case 13:
	  YY_RULE_SETUP
#line 93 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_PAGES;
	    return PAGES;
	  }
	YY_BREAK case 14:
	  YY_RULE_SETUP
#line 98 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_TABLE;
	    return TABLE;
	  }
	YY_BREAK case 15:
	  YY_RULE_SETUP
#line 103 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_DATE;
	    return DATE;
	  }
	YY_BREAK case 16:
	  YY_RULE_SETUP
#line 108 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_SET_VAR;
	    return SET_VAR;
	  }
	YY_BREAK case 17:
	  YY_RULE_SETUP
#line 113 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return IF;
	  }
	YY_BREAK case 18:
	  YY_RULE_SETUP
#line 117 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return ELSE;
	  }
	YY_BREAK case 19:
	  YY_RULE_SETUP
#line 121 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return ELSE_IF;
	  }
	YY_BREAK case 20:
	  YY_RULE_SETUP
#line 125 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return END;
	  }
	YY_BREAK case 21:
	  YY_RULE_SETUP
#line 129 "albumtheme.l"
	  {
	    yylval.ivalue = atoi (yytext);
	    return NUMBER;
	  }
	YY_BREAK case 22:
	  YY_RULE_SETUP
#line 133 "albumtheme.l"
	  {
	    yylval.text = g_strdup (yytext);
	    return NAME;
	  }
	YY_BREAK case 23:
	  YY_RULE_SETUP
#line 137 "albumtheme.l"
	  {
	    return '=';
	  }
	YY_BREAK case 24:
	  YY_RULE_SETUP
#line 140 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_LT;
	    return COMPARE;
	  }
	YY_BREAK case 25:
	  YY_RULE_SETUP
#line 144 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_GT;
	    return COMPARE;
	  }
	YY_BREAK case 26:
	  YY_RULE_SETUP
#line 148 "albumtheme.l"
	  {
	    return '+';
	  }
	YY_BREAK case 27:
	  YY_RULE_SETUP
#line 151 "albumtheme.l"
	  {
	    return '-';
	  }
	YY_BREAK case 28:
	  YY_RULE_SETUP
#line 154 "albumtheme.l"
	  {
	    return '!';
	  }
	YY_BREAK case 29:
	  YY_RULE_SETUP
#line 157 "albumtheme.l"
	  {
	    return '(';
	  }
	YY_BREAK case 30:
	  YY_RULE_SETUP
#line 160 "albumtheme.l"
	  {
	    return ')';
	  }
	YY_BREAK case 31:
	  YY_RULE_SETUP
#line 163 "albumtheme.l"
	  {
	    return '"';
	  }
	YY_BREAK case 32:
	  YY_RULE_SETUP
#line 166 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_AND;
	    return BOOL_OP;
	  }
	YY_BREAK case 33:
	  YY_RULE_SETUP
#line 170 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_OR;
	    return BOOL_OP;
	  }
	YY_BREAK case 34:
	  YY_RULE_SETUP
#line 174 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_EQ;
	    return COMPARE;
	  }
	YY_BREAK case 35:
	  YY_RULE_SETUP
#line 178 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_NE;
	    return COMPARE;
	  }
	YY_BREAK case 36:
	  YY_RULE_SETUP
#line 182 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_LE;
	    return COMPARE;
	  }
	YY_BREAK case 37:
	  YY_RULE_SETUP
#line 186 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_GE;
	    return COMPARE;
	  }
	YY_BREAK case 38:
	  YY_RULE_SETUP
#line 190 "albumtheme.l"
	  {
	    /* Eat spaces inside tag. */
	  }
	YY_BREAK case 39:
	  YY_RULE_SETUP
#line 193 "albumtheme.l"
	  {
	    BEGIN (INITIAL);
	    return END_TAG;
	  }
	YY_BREAK case 40:
	  YY_RULE_SETUP
#line 197 "albumtheme.l"
	  {
	    yylval.text = g_strdup (yytext);
	    return TEXT;
	  }
	YY_BREAK case 41:
	  YY_RULE_SETUP
#line 201 "albumtheme.l"
	  {
	    yylval.text = g_strdup (yytext);
	    return TEXT;
	  }
	YY_BREAK case YY_STATE_EOF (INITIAL):
	case YY_STATE_EOF (TAG):
#line 205 "albumtheme.l"
	  {
	    return 0;
	  }
	YY_BREAK case 42:
	  YY_RULE_SETUP
#line 209 "albumtheme.l"
	    ECHO;
	  YY_BREAK
#line 1164 "lex.yy.c"
	case YY_END_OF_BUFFER:
	  {
	    /* Amount of text matched not including the EOB char. */
	    int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

	    /* Undo the effects of YY_DO_BEFORE_ACTION. */
	    *yy_cp = yy_hold_char;
	    YY_RESTORE_YY_MORE_OFFSET
	      if (yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW)
	      {
		/* We're scanning a new file or input source.  It's
		 * possible that this happened because the user
		 * just pointed yyin at a new source and called
		 * yylex().  If so, then we have to assure
		 * consistency between yy_current_buffer and our
		 * globals.  Here is the right place to do so, because
		 * this is the first action (other than possibly a
		 * back-up) that will match for the new input source.
		 */
		yy_n_chars = yy_current_buffer->yy_n_chars;
		yy_current_buffer->yy_input_file = yyin;
		yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
	      }

	    /* Note that here we test for yy_c_buf_p "<=" to the position
	     * of the first EOB in the buffer, since yy_c_buf_p will
	     * already have been incremented past the NUL character
	     * (since all states make transitions on EOB to the
	     * end-of-buffer state).  Contrast this with the test
	     * in input().
	     */
	    if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars])
	      {			/* This was really a NUL. */
		yy_state_type yy_next_state;

		yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

		yy_current_state = yy_get_previous_state ();

		/* Okay, we're now positioned to make the NUL
		 * transition.  We couldn't have
		 * yy_get_previous_state() go ahead and do it
		 * for us because it doesn't know how to deal
		 * with the possibility of jamming (and we don't
		 * want to build jamming into it because then it
		 * will run more slowly).
		 */

		yy_next_state = yy_try_NUL_trans (yy_current_state);

		yy_bp = yytext_ptr + YY_MORE_ADJ;

		if (yy_next_state)
		  {
		    /* Consume the NUL. */
		    yy_cp = ++yy_c_buf_p;
		    yy_current_state = yy_next_state;
		    goto yy_match;
		  }

		else
		  {
		    yy_cp = yy_c_buf_p;
		    goto yy_find_action;
		  }
	      }

	    else
	      switch (yy_get_next_buffer ())
		{
		case EOB_ACT_END_OF_FILE:
		  {
		    yy_did_buffer_switch_on_eof = 0;

		    if (yywrap ())
		      {
			/* Note: because we've taken care in
			 * yy_get_next_buffer() to have set up
			 * yytext, we can now set up
			 * yy_c_buf_p so that if some total
			 * hoser (like flex itself) wants to
			 * call the scanner after we return the
			 * YY_NULL, it'll still work - another
			 * YY_NULL will get returned.
			 */
			yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

			yy_act = YY_STATE_EOF (YY_START);
			goto do_action;
		      }

		    else
		      {
			if (!yy_did_buffer_switch_on_eof)
			  YY_NEW_FILE;
		      }
		    break;
		  }

		case EOB_ACT_CONTINUE_SCAN:
		  yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

		  yy_current_state = yy_get_previous_state ();

		  yy_cp = yy_c_buf_p;
		  yy_bp = yytext_ptr + YY_MORE_ADJ;
		  goto yy_match;

		case EOB_ACT_LAST_MATCH:
		  yy_c_buf_p = &yy_current_buffer->yy_ch_buf[yy_n_chars];

		  yy_current_state = yy_get_previous_state ();

		  yy_cp = yy_c_buf_p;
		  yy_bp = yytext_ptr + YY_MORE_ADJ;
		  goto yy_find_action;
		}
	    break;
	  }

	default:
	  YY_FATAL_ERROR
	    ("fatal flex scanner internal error--no action found");
	}			/* end of action switch */
    }				/* end of scanning one token */
}				/* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int
yy_get_next_buffer ()
{
  register char *dest = yy_current_buffer->yy_ch_buf;
  register char *source = yytext_ptr;
  register int number_to_move, i;
  int ret_val;

  if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1])
    YY_FATAL_ERROR
      ("fatal flex scanner internal error--end of buffer missed");

  if (yy_current_buffer->yy_fill_buffer == 0)
    {				/* Don't try to fill the buffer, so this is an EOF. */
      if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1)
	{
	  /* We matched a single character, the EOB, so
	   * treat this as a final EOF.
	   */
	  return EOB_ACT_END_OF_FILE;
	}

      else
	{
	  /* We matched some text prior to the EOB, first
	   * process it.
	   */
	  return EOB_ACT_LAST_MATCH;
	}
    }

  /* Try to read more data. */

  /* First move last chars to start of buffer. */
  number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

  for (i = 0; i < number_to_move; ++i)
    *(dest++) = *(source++);

  if (yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING)
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
    yy_current_buffer->yy_n_chars = yy_n_chars = 0;

  else
    {
      int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

      while (num_to_read <= 0)
	{			/* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
	  YY_FATAL_ERROR
	    ("input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

	  /* just a shorter name for the current buffer */
	  YY_BUFFER_STATE b = yy_current_buffer;

	  int yy_c_buf_p_offset = (int) (yy_c_buf_p - b->yy_ch_buf);

	  if (b->yy_is_our_buffer)
	    {
	      int new_size = b->yy_buf_size * 2;

	      if (new_size <= 0)
		b->yy_buf_size += b->yy_buf_size / 8;
	      else
		b->yy_buf_size *= 2;

	      b->yy_ch_buf = (char *)
		/* Include room in for 2 EOB chars. */
		yy_flex_realloc ((void *) b->yy_ch_buf, b->yy_buf_size + 2);
	    }
	  else
	    /* Can't grow it, we don't own it. */
	    b->yy_ch_buf = 0;

	  if (!b->yy_ch_buf)
	    YY_FATAL_ERROR ("fatal error - scanner input buffer overflow");

	  yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

	  num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;
#endif
	}

      if (num_to_read > YY_READ_BUF_SIZE)
	num_to_read = YY_READ_BUF_SIZE;

      /* Read in more data. */
      YY_INPUT ((&yy_current_buffer->yy_ch_buf[number_to_move]),
		yy_n_chars, num_to_read);

      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  if (yy_n_chars == 0)
    {
      if (number_to_move == YY_MORE_ADJ)
	{
	  ret_val = EOB_ACT_END_OF_FILE;
	  yyrestart (yyin);
	}

      else
	{
	  ret_val = EOB_ACT_LAST_MATCH;
	  yy_current_buffer->yy_buffer_status = YY_BUFFER_EOF_PENDING;
	}
    }

  else
    ret_val = EOB_ACT_CONTINUE_SCAN;

  yy_n_chars += number_to_move;
  yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
  yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

  yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

  return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type
yy_get_previous_state ()
{
  register yy_state_type yy_current_state;
  register char *yy_cp;

  yy_current_state = yy_start;

  for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp)
    {
      register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI (*yy_cp)] : 1);
      if (yy_accept[yy_current_state])
	{
	  yy_last_accepting_state = yy_current_state;
	  yy_last_accepting_cpos = yy_cp;
	}
      while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	{
	  yy_current_state = (int) yy_def[yy_current_state];
	  if (yy_current_state >= 224)
	    yy_c = yy_meta[(unsigned int) yy_c];
	}
      yy_current_state =
	yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    }

  return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type
yy_try_NUL_trans (yy_state_type yy_current_state)
#else
static yy_state_type
yy_try_NUL_trans (yy_current_state)
     yy_state_type yy_current_state;
#endif
{
  register int yy_is_jam;
  register char *yy_cp = yy_c_buf_p;

  register YY_CHAR yy_c = 1;
  if (yy_accept[yy_current_state])
    {
      yy_last_accepting_state = yy_current_state;
      yy_last_accepting_cpos = yy_cp;
    }
  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
      yy_current_state = (int) yy_def[yy_current_state];
      if (yy_current_state >= 224)
	yy_c = yy_meta[(unsigned int) yy_c];
    }
  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
  yy_is_jam = (yy_current_state == 223);

  return yy_is_jam ? 0 : yy_current_state;
}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void
yyunput (int c, register char *yy_bp)
#else
static void
yyunput (c, yy_bp)
     int c;
     register char *yy_bp;
#endif
{
  register char *yy_cp = yy_c_buf_p;

  /* undo effects of setting up yytext */
  *yy_cp = yy_hold_char;

  if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
    {				/* need to shift things up to make room */
      /* +2 for EOB chars. */
      register int number_to_move = yy_n_chars + 2;
      register char *dest =
	&yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
      register char *source = &yy_current_buffer->yy_ch_buf[number_to_move];

      while (source > yy_current_buffer->yy_ch_buf)
	*--dest = *--source;

      yy_cp += (int) (dest - source);
      yy_bp += (int) (dest - source);
      yy_current_buffer->yy_n_chars =
	yy_n_chars = yy_current_buffer->yy_buf_size;

      if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
	YY_FATAL_ERROR ("flex scanner push-back overflow");
    }

  *--yy_cp = (char) c;


  yytext_ptr = yy_bp;
  yy_hold_char = *yy_cp;
  yy_c_buf_p = yy_cp;
}
#endif /* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int
yyinput ()
#else
static int
input ()
#endif
{
  int c;

  *yy_c_buf_p = yy_hold_char;

  if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR)
    {
      /* yy_c_buf_p now points to the character we want to return.
       * If this occurs *before* the EOB characters, then it's a
       * valid NUL; if not, then we've hit the end of the buffer.
       */
      if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
	/* This was really a NUL. */
	*yy_c_buf_p = '\0';

      else
	{			/* need more input */
	  int offset = yy_c_buf_p - yytext_ptr;
	  ++yy_c_buf_p;

	  switch (yy_get_next_buffer ())
	    {
	    case EOB_ACT_LAST_MATCH:
	      /* This happens because yy_g_n_b()
	       * sees that we've accumulated a
	       * token and flags that we need to
	       * try matching the token before
	       * proceeding.  But for input(),
	       * there's no matching to consider.
	       * So convert the EOB_ACT_LAST_MATCH
	       * to EOB_ACT_END_OF_FILE.
	       */

	      /* Reset buffer status. */
	      yyrestart (yyin);

	      /* fall through */

	    case EOB_ACT_END_OF_FILE:
	      {
		if (yywrap ())
		  return EOF;

		if (!yy_did_buffer_switch_on_eof)
		  YY_NEW_FILE;
#ifdef __cplusplus
		return yyinput ();
#else
		return input ();
#endif
	      }

	    case EOB_ACT_CONTINUE_SCAN:
	      yy_c_buf_p = yytext_ptr + offset;
	      break;
	    }
	}
    }

  c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
  *yy_c_buf_p = '\0';		/* preserve yytext */
  yy_hold_char = *++yy_c_buf_p;


  return c;
}


#ifdef YY_USE_PROTOS
void
yyrestart (FILE * input_file)
#else
void
yyrestart (input_file)
     FILE *input_file;
#endif
{
  if (!yy_current_buffer)
    yy_current_buffer = yy_create_buffer (yyin, YY_BUF_SIZE);

  yy_init_buffer (yy_current_buffer, input_file);
  yy_load_buffer_state ();
}


#ifdef YY_USE_PROTOS
void
yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
#else
void
yy_switch_to_buffer (new_buffer)
     YY_BUFFER_STATE new_buffer;
#endif
{
  if (yy_current_buffer == new_buffer)
    return;

  if (yy_current_buffer)
    {
      /* Flush out information for old buffer. */
      *yy_c_buf_p = yy_hold_char;
      yy_current_buffer->yy_buf_pos = yy_c_buf_p;
      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  yy_current_buffer = new_buffer;
  yy_load_buffer_state ();

  /* We don't actually know whether we did this switch during
   * EOF (yywrap()) processing, but the only time this flag
   * is looked at is after yywrap() is called, so it's safe
   * to go ahead and always set it.
   */
  yy_did_buffer_switch_on_eof = 1;
}


#ifdef YY_USE_PROTOS
void
yy_load_buffer_state (void)
#else
void
yy_load_buffer_state ()
#endif
{
  yy_n_chars = yy_current_buffer->yy_n_chars;
  yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
  yyin = yy_current_buffer->yy_input_file;
  yy_hold_char = *yy_c_buf_p;
}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_create_buffer (FILE * file, int size)
#else
YY_BUFFER_STATE
yy_create_buffer (file, size)
     FILE *file;
     int size;
#endif
{
  YY_BUFFER_STATE b;

  b = (YY_BUFFER_STATE) yy_flex_alloc (sizeof (struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR ("out of dynamic memory in yy_create_buffer()");

  b->yy_buf_size = size;

  /* yy_ch_buf has to be 2 characters longer than the size given because
   * we need to put in 2 end-of-buffer characters.
   */
  b->yy_ch_buf = (char *) yy_flex_alloc (b->yy_buf_size + 2);
  if (!b->yy_ch_buf)
    YY_FATAL_ERROR ("out of dynamic memory in yy_create_buffer()");

  b->yy_is_our_buffer = 1;

  yy_init_buffer (b, file);

  return b;
}


#ifdef YY_USE_PROTOS
void
yy_delete_buffer (YY_BUFFER_STATE b)
#else
void
yy_delete_buffer (b)
     YY_BUFFER_STATE b;
#endif
{
  if (!b)
    return;

  if (b == yy_current_buffer)
    yy_current_buffer = (YY_BUFFER_STATE) 0;

  if (b->yy_is_our_buffer)
    yy_flex_free ((void *) b->yy_ch_buf);

  yy_flex_free ((void *) b);
}



#ifdef YY_USE_PROTOS
void
yy_init_buffer (YY_BUFFER_STATE b, FILE * file)
#else
void
yy_init_buffer (b, file)
     YY_BUFFER_STATE b;
     FILE *file;
#endif


{
  yy_flush_buffer (b);

  b->yy_input_file = file;
  b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
  b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
  b->yy_is_interactive = 0;
#else
  b->yy_is_interactive = file ? (isatty (fileno (file)) > 0) : 0;
#endif
#endif
}


#ifdef YY_USE_PROTOS
void
yy_flush_buffer (YY_BUFFER_STATE b)
#else
void
yy_flush_buffer (b)
     YY_BUFFER_STATE b;
#endif

{
  if (!b)
    return;

  b->yy_n_chars = 0;

  /* We always need two end-of-buffer characters.  The first causes
   * a transition to the end-of-buffer state.  The second causes
   * a jam in that state.
   */
  b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
  b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

  b->yy_buf_pos = &b->yy_ch_buf[0];

  b->yy_at_bol = 1;
  b->yy_buffer_status = YY_BUFFER_NEW;

  if (b == yy_current_buffer)
    yy_load_buffer_state ();
}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_buffer (char *base, yy_size_t size)
#else
YY_BUFFER_STATE
yy_scan_buffer (base, size)
     char *base;
     yy_size_t size;
#endif
{
  YY_BUFFER_STATE b;

  if (size < 2 ||
      base[size - 2] != YY_END_OF_BUFFER_CHAR ||
      base[size - 1] != YY_END_OF_BUFFER_CHAR)
    /* They forgot to leave room for the EOB's. */
    return 0;

  b = (YY_BUFFER_STATE) yy_flex_alloc (sizeof (struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR ("out of dynamic memory in yy_scan_buffer()");

  b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
  b->yy_buf_pos = b->yy_ch_buf = base;
  b->yy_is_our_buffer = 0;
  b->yy_input_file = 0;
  b->yy_n_chars = b->yy_buf_size;
  b->yy_is_interactive = 0;
  b->yy_at_bol = 1;
  b->yy_fill_buffer = 0;
  b->yy_buffer_status = YY_BUFFER_NEW;

  yy_switch_to_buffer (b);

  return b;
}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_string (yyconst char *yy_str)
#else
YY_BUFFER_STATE
yy_scan_string (yy_str)
     yyconst char *yy_str;
#endif
{
  int len;
  for (len = 0; yy_str[len]; ++len)
    ;

  return yy_scan_bytes (yy_str, len);
}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_bytes (yyconst char *bytes, int len)
#else
YY_BUFFER_STATE
yy_scan_bytes (bytes, len)
     yyconst char *bytes;
     int len;
#endif
{
  YY_BUFFER_STATE b;
  char *buf;
  yy_size_t n;
  int i;

  /* Get memory for full buffer, including space for trailing EOB's. */
  n = len + 2;
  buf = (char *) yy_flex_alloc (n);
  if (!buf)
    YY_FATAL_ERROR ("out of dynamic memory in yy_scan_bytes()");

  for (i = 0; i < len; ++i)
    buf[i] = bytes[i];

  buf[len] = buf[len + 1] = YY_END_OF_BUFFER_CHAR;

  b = yy_scan_buffer (buf, n);
  if (!b)
    YY_FATAL_ERROR ("bad buffer in yy_scan_bytes()");

  /* It's okay to grow etc. this buffer, and we should throw it
   * away when we're done.
   */
  b->yy_is_our_buffer = 1;

  return b;
}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void
yy_push_state (int new_state)
#else
static void
yy_push_state (new_state)
     int new_state;
#endif
{
  if (yy_start_stack_ptr >= yy_start_stack_depth)
    {
      yy_size_t new_size;

      yy_start_stack_depth += YY_START_STACK_INCR;
      new_size = yy_start_stack_depth * sizeof (int);

      if (!yy_start_stack)
	yy_start_stack = (int *) yy_flex_alloc (new_size);

      else
	yy_start_stack = (int *) yy_flex_realloc ((void *) yy_start_stack,
						  new_size);

      if (!yy_start_stack)
	YY_FATAL_ERROR ("out of memory expanding start-condition stack");
    }

  yy_start_stack[yy_start_stack_ptr++] = YY_START;

  BEGIN (new_state);
}
#endif


#ifndef YY_NO_POP_STATE
static void
yy_pop_state ()
{
  if (--yy_start_stack_ptr < 0)
    YY_FATAL_ERROR ("start-condition stack underflow");

  BEGIN (yy_start_stack[yy_start_stack_ptr]);
}
#endif


#ifndef YY_NO_TOP_STATE
static int
yy_top_state ()
{
  return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void
yy_fatal_error (yyconst char msg[])
#else
static void
yy_fatal_error (msg)
     char msg[];
#endif
{
  (void) fprintf (stderr, "%s\n", msg);
  exit (YY_EXIT_FAILURE);
}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void
yy_flex_strncpy (char *s1, yyconst char *s2, int n)
#else
static void
yy_flex_strncpy (s1, s2, n)
     char *s1;
     yyconst char *s2;
     int n;
#endif
{
  register int i;
  for (i = 0; i < n; ++i)
    s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int
yy_flex_strlen (yyconst char *s)
#else
static int
yy_flex_strlen (s)
     yyconst char *s;
#endif
{
  register int n;
  for (n = 0; s[n]; ++n)
    ;

  return n;
}
#endif


#ifdef YY_USE_PROTOS
static void *
yy_flex_alloc (yy_size_t size)
#else
static void *
yy_flex_alloc (size)
     yy_size_t size;
#endif
{
  return (void *) malloc (size);
}

#ifdef YY_USE_PROTOS
static void *
yy_flex_realloc (void *ptr, yy_size_t size)
#else
static void *
yy_flex_realloc (ptr, size)
     void *ptr;
     yy_size_t size;
#endif
{
  /* The cast to (char *) in the following accommodates both
   * implementations that use char* generic pointers, and those
   * that use void* generic pointers.  It works with the latter
   * because both ANSI C and C++ allow castless assignment from
   * any pointer type to void*, and deal with argument conversions
   * as though doing an assignment.
   */
  return (void *) realloc ((char *) ptr, size);
}

#ifdef YY_USE_PROTOS
static void
yy_flex_free (void *ptr)
#else
static void
yy_flex_free (ptr)
     void *ptr;
#endif
{
  free (ptr);
}

#if YY_MAIN
int
main ()
{
  yylex ();
  return 0;
}
#endif
#line 209 "albumtheme.l"
