/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else /* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif /* __STDC__ */
#endif /* ! __cplusplus */

#ifdef __TURBOC__
#pragma warn -rch
#pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
{
  FILE *yy_input_file;

  char *yy_ch_buf;		/* input buffer */
  char *yy_buf_pos;		/* current position in input buffer */

  /* Size of input buffer in bytes, not including room for EOB
   * characters.
   */
  yy_size_t yy_buf_size;

  /* Number of characters read into yy_ch_buf, not including EOB
   * characters.
   */
  int yy_n_chars;

  /* Whether we "own" the buffer - i.e., we know we created it,
   * and can realloc() it to grow it, and should free() it to
   * delete it.
   */
  int yy_is_our_buffer;

  /* Whether this is an "interactive" input source; if so, and
   * if we're using stdio for input, then we want to use getc()
   * instead of fread(), to make sure we stop fetching input after
   * each newline.
   */
  int yy_is_interactive;

  /* Whether we're considered to be at the beginning of a line.
   * If so, '^' rules will be active on the next match, otherwise
   * not.
   */
  int yy_at_bol;

  /* Whether to try to fill the input buffer when we reach the
   * end of it.
   */
  int yy_fill_buffer;

  int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
  /* When an EOF's been seen but there's still some text to process
   * then we mark the buffer as YY_EOF_PENDING, to indicate that we
   * shouldn't try reading from the input source any more.  We might
   * still have a bunch of tokens to match, though, because of
   * possible backing-up.
   *
   * When we actually see the EOF, we change the status to "new"
   * (via yyrestart()), so that the user can continue scanning by
   * just pointing yyin at a new input file.
   */
#define YY_BUFFER_EOF_PENDING 2
};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO ((FILE * input_file));

void yy_switch_to_buffer YY_PROTO ((YY_BUFFER_STATE new_buffer));
void yy_load_buffer_state YY_PROTO ((void));
YY_BUFFER_STATE yy_create_buffer YY_PROTO ((FILE * file, int size));
void yy_delete_buffer YY_PROTO ((YY_BUFFER_STATE b));
void yy_init_buffer YY_PROTO ((YY_BUFFER_STATE b, FILE * file));
void yy_flush_buffer YY_PROTO ((YY_BUFFER_STATE b));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO ((char *base, yy_size_t size));
YY_BUFFER_STATE yy_scan_string YY_PROTO ((yyconst char *yy_str));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO ((yyconst char *bytes, int len));

static void *yy_flex_alloc YY_PROTO ((yy_size_t));
static void *yy_flex_realloc YY_PROTO ((void *, yy_size_t));
static void yy_flex_free YY_PROTO ((void *));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO ((void));
static yy_state_type yy_try_NUL_trans
YY_PROTO ((yy_state_type current_state));
static int yy_get_next_buffer YY_PROTO ((void));
static void yy_fatal_error YY_PROTO ((yyconst char msg[]));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
static yyconst short int yy_accept[340] = { 0,
  0, 0, 0, 0, 0, 0, 58, 56, 55, 57,
  53, 43, 46, 57, 44, 45, 41, 39, 40, 42,
  33, 36, 35, 37, 34, 57, 42, 38, 56, 0,
  0, 50, 47, 54, 33, 51, 49, 52, 34, 48,
  56, 0, 0, 56, 0, 0, 56, 0, 0, 56,
  0, 0, 56, 0, 0, 56, 0, 0, 56, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 56,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  29, 0, 0, 0, 0, 0, 56, 0, 0, 0,
  0, 32, 0, 0, 0, 0, 0, 0, 0, 0,

  0, 0, 56, 0, 0, 16, 30, 28, 0, 0,
  0, 0, 0, 0, 0, 0, 17, 56, 0, 0,
  0, 0, 0, 0, 0, 3, 0, 14, 0, 15,
  56, 18, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 2, 1, 0, 7, 0, 0, 0,
  56, 11, 31, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 27, 56,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 13, 0, 56, 0, 0, 0, 0,
  0, 0, 0, 8, 9, 10, 6, 5, 0, 12,

  56, 0, 0, 0, 0, 21, 0, 0, 4, 56,
  0, 0, 0, 0, 0, 0, 56, 0, 0, 0,
  0, 0, 0, 56, 0, 0, 0, 0, 0, 0,
  56, 0, 0, 25, 0, 0, 0, 56, 0, 0,
  0, 0, 0, 0, 56, 0, 0, 0, 0, 0,
  0, 56, 0, 26, 0, 0, 24, 0, 56, 0,
  20, 19, 22, 56, 23, 56, 56, 56, 56, 56,
  56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
  56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
  56, 56, 56, 56, 56, 56, 56, 56, 56, 56,

  56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
  56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
  56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
  56, 56, 56, 56, 56, 56, 56, 56, 0
};

static yyconst int yy_ec[256] = { 0,
  1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 2, 3, 4, 1, 1, 1, 5, 1, 6,
  7, 8, 9, 1, 10, 1, 11, 12, 12, 12,
  12, 12, 12, 12, 12, 12, 12, 13, 1, 14,
  15, 16, 1, 17, 18, 18, 18, 18, 18, 18,
  18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
  18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
  1, 1, 1, 1, 19, 1, 20, 21, 22, 23,

  24, 25, 26, 27, 28, 18, 29, 30, 31, 32,
  33, 34, 18, 35, 36, 37, 38, 39, 18, 40,
  18, 41, 1, 42, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1
};

static yyconst int yy_meta[43] = { 0,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 2, 2, 3, 1, 1, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  2, 1
};

static yyconst short int yy_base[441] = { 0,
  449, 448, 0, 0, 32, 33, 461, 0, 34, 464,
  464, 445, 464, 454, 464, 464, 464, 464, 464, 442,
  445, 441, 440, 439, 0, 411, 464, 437, 0, 425,
  413, 464, 464, 464, 437, 464, 464, 464, 0, 464,
  0, 411, 420, 0, 419, 407, 0, 406, 412, 0,
  411, 420, 0, 419, 426, 0, 425, 39, 0, 400,
  403, 415, 38, 18, 410, 22, 413, 408, 30, 0,
  407, 399, 392, 392, 404, 406, 397, 394, 390, 402,
  464, 401, 394, 382, 397, 377, 0, 376, 384, 390,
  389, 464, 382, 386, 386, 372, 385, 381, 382, 386,

  374, 366, 0, 365, 377, 464, 381, 464, 386, 379,
  373, 372, 371, 33, 355, 369, 464, 0, 376, 359,
  362, 59, 23, 354, 353, 52, 28, 464, 367, 464,
  0, 464, 349, 360, 350, 363, 362, 341, 56, 353,
  359, 358, 349, 464, 464, 57, 464, 353, 347, 339,
  0, 464, 464, 349, 341, 334, 336, 349, 346, 329,
  335, 328, 323, 335, 339, 333, 320, 327, 464, 0,
  323, 333, 332, 322, 318, 333, 315, 327, 323, 325,
  317, 307, 314, 464, 316, 0, 307, 308, 323, 305,
  313, 309, 301, 464, 464, 464, 464, 464, 308, 464,

  0, 298, 315, 297, 295, 464, 313, 307, 464, 0,
  295, 310, 300, 292, 296, 290, 0, 300, 292, 291,
  297, 296, 300, 0, 299, 284, 292, 296, 282, 277,
  0, 273, 288, 464, 59, 284, 275, 0, 288, 283,
  273, 277, 267, 279, 0, 272, 271, 277, 268, 271,
  70, 0, 55, 464, 68, 67, 464, 51, 0, 48,
  464, 464, 464, 0, 464, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 464, 464, 96,
  99, 63, 101, 103, 105, 107, 109, 111, 113, 115,
  117, 119, 121, 123, 125, 127, 129, 131, 133, 135,
  137, 139, 141, 143, 145, 147, 149, 151, 153, 155,
  157, 159, 161, 163, 165, 167, 169, 171, 173, 175,
  177, 179, 181, 183, 185, 187, 189, 191, 193, 195,
  197, 199, 201, 203, 205, 207, 209, 211, 213, 215,

  217, 219, 221, 223, 225, 227, 229, 231, 233, 235,
  237, 239, 241, 243, 245, 247, 249, 251, 253, 255,
  257, 259, 261, 263, 265, 267, 269, 271, 273, 275,
  277, 279, 281, 283, 285, 287, 289, 291, 293, 295
};

static yyconst short int yy_def[441] = { 0,
  340, 340, 339, 3, 3, 3, 339, 341, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 342, 339, 339, 339, 343, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 342, 339,
  344, 339, 339, 345, 339, 339, 346, 339, 339, 347,
  339, 339, 348, 339, 339, 349, 339, 339, 350, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 351,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 352, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,

  339, 339, 353, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 354, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  355, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  356, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 357,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 358, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,

  359, 339, 339, 339, 339, 339, 339, 339, 339, 360,
  339, 339, 339, 339, 339, 339, 361, 339, 339, 339,
  339, 339, 339, 362, 339, 339, 339, 339, 339, 339,
  363, 339, 339, 339, 339, 339, 339, 364, 339, 339,
  339, 339, 339, 339, 365, 339, 339, 339, 339, 339,
  339, 366, 339, 339, 339, 339, 339, 339, 367, 339,
  339, 339, 339, 368, 339, 369, 370, 371, 372, 373,
  374, 375, 376, 377, 378, 379, 380, 381, 382, 383,
  384, 385, 386, 387, 388, 389, 390, 391, 392, 393,
  394, 395, 396, 397, 398, 399, 400, 401, 402, 403,

  404, 405, 406, 407, 408, 409, 410, 411, 412, 413,
  414, 415, 416, 417, 418, 419, 420, 421, 422, 423,
  424, 425, 426, 427, 428, 429, 430, 431, 432, 433,
  434, 435, 436, 437, 438, 439, 440, 339, 0, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,

  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339
};

static yyconst short int yy_nxt[507] = { 0,
  10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
  20, 21, 10, 22, 23, 24, 10, 25, 25, 25,
  25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
  25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
  25, 26, 27, 27, 30, 78, 81, 28, 28, 85,
  79, 127, 82, 86, 141, 148, 142, 149, 143, 31,
  61, 62, 63, 64, 39, 65, 66, 74, 128, 75,
  146, 265, 67, 263, 68, 69, 76, 77, 135, 164,
  136, 137, 138, 139, 165, 158, 166, 147, 159, 241,
  262, 261, 260, 258, 140, 242, 8, 8, 8, 29,

  29, 41, 41, 44, 44, 47, 47, 50, 50, 53,
  53, 56, 56, 59, 59, 70, 70, 87, 87, 103,
  103, 118, 118, 131, 131, 151, 151, 170, 170, 186,
  186, 201, 201, 210, 210, 217, 217, 224, 224, 231,
  231, 238, 238, 245, 245, 252, 252, 259, 259, 264,
  264, 266, 266, 267, 267, 268, 268, 269, 269, 270,
  270, 271, 271, 272, 272, 273, 273, 274, 274, 275,
  275, 276, 276, 277, 277, 278, 278, 279, 279, 280,
  280, 281, 281, 282, 282, 283, 283, 284, 284, 285,
  285, 286, 286, 287, 287, 288, 288, 289, 289, 290,

  290, 291, 291, 292, 292, 293, 293, 294, 294, 295,
  295, 296, 296, 297, 297, 298, 298, 299, 299, 300,
  300, 301, 301, 302, 302, 303, 303, 304, 304, 305,
  305, 306, 306, 307, 307, 308, 308, 309, 309, 310,
  310, 311, 311, 312, 312, 313, 313, 314, 314, 315,
  315, 316, 316, 317, 317, 318, 318, 319, 319, 320,
  320, 321, 321, 322, 322, 323, 323, 324, 324, 325,
  325, 326, 326, 327, 327, 328, 328, 329, 329, 330,
  330, 331, 331, 332, 332, 333, 333, 334, 334, 335,
  335, 336, 336, 337, 337, 338, 338, 257, 256, 255,

  254, 253, 251, 250, 249, 248, 247, 246, 244, 243,
  240, 239, 237, 236, 235, 234, 233, 232, 230, 229,
  228, 227, 226, 225, 223, 222, 221, 220, 219, 218,
  216, 215, 214, 213, 212, 211, 209, 208, 207, 206,
  205, 204, 203, 202, 200, 199, 198, 197, 196, 195,
  194, 193, 192, 191, 190, 189, 188, 187, 185, 184,
  183, 182, 181, 180, 179, 178, 177, 176, 175, 174,
  173, 172, 171, 169, 168, 167, 163, 162, 161, 160,
  157, 156, 155, 154, 153, 152, 150, 145, 144, 134,
  133, 132, 130, 129, 126, 125, 124, 123, 122, 121,

  120, 119, 117, 116, 115, 114, 113, 112, 111, 110,
  109, 108, 107, 106, 105, 104, 102, 101, 100, 99,
  98, 97, 96, 95, 94, 93, 92, 91, 90, 89,
  88, 84, 83, 80, 73, 72, 71, 60, 58, 57,
  55, 54, 52, 51, 49, 48, 46, 45, 35, 43,
  42, 38, 40, 38, 37, 36, 35, 34, 33, 32,
  339, 9, 9, 7, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,

  339, 339, 339, 339, 339, 339
};

static yyconst short int yy_chk[507] = { 0,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
  3, 3, 5, 6, 9, 64, 66, 5, 6, 69,
  64, 114, 66, 69, 123, 127, 123, 127, 123, 9,
  58, 58, 58, 58, 342, 58, 58, 63, 114, 63,
  126, 260, 58, 258, 58, 58, 63, 63, 122, 146,
  122, 122, 122, 122, 146, 139, 146, 126, 139, 235,
  256, 255, 253, 251, 122, 235, 340, 340, 340, 341,

  341, 343, 343, 344, 344, 345, 345, 346, 346, 347,
  347, 348, 348, 349, 349, 350, 350, 351, 351, 352,
  352, 353, 353, 354, 354, 355, 355, 356, 356, 357,
  357, 358, 358, 359, 359, 360, 360, 361, 361, 362,
  362, 363, 363, 364, 364, 365, 365, 366, 366, 367,
  367, 368, 368, 369, 369, 370, 370, 371, 371, 372,
  372, 373, 373, 374, 374, 375, 375, 376, 376, 377,
  377, 378, 378, 379, 379, 380, 380, 381, 381, 382,
  382, 383, 383, 384, 384, 385, 385, 386, 386, 387,
  387, 388, 388, 389, 389, 390, 390, 391, 391, 392,

  392, 393, 393, 394, 394, 395, 395, 396, 396, 397,
  397, 398, 398, 399, 399, 400, 400, 401, 401, 402,
  402, 403, 403, 404, 404, 405, 405, 406, 406, 407,
  407, 408, 408, 409, 409, 410, 410, 411, 411, 412,
  412, 413, 413, 414, 414, 415, 415, 416, 416, 417,
  417, 418, 418, 419, 419, 420, 420, 421, 421, 422,
  422, 423, 423, 424, 424, 425, 425, 426, 426, 427,
  427, 428, 428, 429, 429, 430, 430, 431, 431, 432,
  432, 433, 433, 434, 434, 435, 435, 436, 436, 437,
  437, 438, 438, 439, 439, 440, 440, 250, 249, 248,

  247, 246, 244, 243, 242, 241, 240, 239, 237, 236,
  233, 232, 230, 229, 228, 227, 226, 225, 223, 222,
  221, 220, 219, 218, 216, 215, 214, 213, 212, 211,
  208, 207, 205, 204, 203, 202, 199, 193, 192, 191,
  190, 189, 188, 187, 185, 183, 182, 181, 180, 179,
  178, 177, 176, 175, 174, 173, 172, 171, 168, 167,
  166, 165, 164, 163, 162, 161, 160, 159, 158, 157,
  156, 155, 154, 150, 149, 148, 143, 142, 141, 140,
  138, 137, 136, 135, 134, 133, 129, 125, 124, 121,
  120, 119, 116, 115, 113, 112, 111, 110, 109, 107,

  105, 104, 102, 101, 100, 99, 98, 97, 96, 95,
  94, 93, 91, 90, 89, 88, 86, 85, 84, 83,
  82, 80, 79, 78, 77, 76, 75, 74, 73, 72,
  71, 68, 67, 65, 62, 61, 60, 57, 55, 54,
  52, 51, 49, 48, 46, 45, 43, 42, 35, 31,
  30, 28, 26, 24, 23, 22, 21, 20, 14, 12,
  7, 2, 1, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,
  339, 339, 339, 339, 339, 339, 339, 339, 339, 339,

  339, 339, 339, 339, 339, 339
};

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "albumtheme.l"
#define INITIAL 0
#line 2 "albumtheme.l"
/*
 *  GThumb
 *
 *  Copyright (C) 2003 Free Software Foundation, Inc.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Street #330, Boston, MA 02111-1307, USA.
 */

#include <glib.h>

#define TAG 1
#define STAG 2

#line 633 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO ((void));
#else
extern int yywrap YY_PROTO ((void));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO ((int c, char *buf_ptr));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO ((char *, yyconst char *, int));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO ((yyconst char *));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO ((void));
#else
static int input YY_PROTO ((void));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO ((int new_state));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO ((void));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO ((void));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
{
  register yy_state_type yy_current_state;
  register char *yy_cp = NULL, *yy_bp = NULL;
  register int yy_act;

#line 31 "albumtheme.l"


#line 787 "lex.yy.c"

  if (yy_init)
    {
      yy_init = 0;

#ifdef YY_USER_INIT
      YY_USER_INIT;
#endif

      if (!yy_start)
	yy_start = 1;		/* first start state */

      if (!yyin)
	yyin = stdin;

      if (!yyout)
	yyout = stdout;

      if (!yy_current_buffer)
	yy_current_buffer = yy_create_buffer (yyin, YY_BUF_SIZE);

      yy_load_buffer_state ();
    }

  while (1)			/* loops until end-of-file is reached */
    {
      yy_cp = yy_c_buf_p;

      /* Support of yytext. */
      *yy_cp = yy_hold_char;

      /* yy_bp points to the position in yy_ch_buf of the start of
       * the current run.
       */
      yy_bp = yy_cp;

      yy_current_state = yy_start;
    yy_match:
      do
	{
	  register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI (*yy_cp)];
	  if (yy_accept[yy_current_state])
	    {
	      yy_last_accepting_state = yy_current_state;
	      yy_last_accepting_cpos = yy_cp;
	    }
	  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	    {
	      yy_current_state = (int) yy_def[yy_current_state];
	      if (yy_current_state >= 340)
		yy_c = yy_meta[(unsigned int) yy_c];
	    }
	  yy_current_state =
	    yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	  ++yy_cp;
	}
      while (yy_base[yy_current_state] != 464);

    yy_find_action:
      yy_act = yy_accept[yy_current_state];
      if (yy_act == 0)
	{			/* have to back up */
	  yy_cp = yy_last_accepting_cpos;
	  yy_current_state = yy_last_accepting_state;
	  yy_act = yy_accept[yy_current_state];
	}

      YY_DO_BEFORE_ACTION;


    do_action:			/* This label is used only to access EOF actions. */


      switch (yy_act)
	{			/* beginning of action switch */
	case 0:		/* must back up */
	  /* undo the effects of YY_DO_BEFORE_ACTION */
	  *yy_cp = yy_hold_char;
	  yy_cp = yy_last_accepting_cpos;
	  yy_current_state = yy_last_accepting_state;
	  goto yy_find_action;

	case 1:
	  YY_RULE_SETUP
#line 33 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_HEADER;
	    return HEADER;
	  }
	YY_BREAK case 2:
	  YY_RULE_SETUP
#line 38 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_FOOTER;
	    return FOOTER;
	  }
	YY_BREAK case 3:
	  YY_RULE_SETUP
#line 43 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE;
	    return IMAGE;
	  }
	YY_BREAK case 4:
	  YY_RULE_SETUP
#line 48 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE_LINK;
	    return IMAGE_LINK;
	  }
	YY_BREAK case 5:
	  YY_RULE_SETUP
#line 53 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE_IDX;
	    return IMAGE_IDX;
	  }
	YY_BREAK case 6:
	  YY_RULE_SETUP
#line 58 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGE_DIM;
	    return IMAGE_DIM;
	  }
	YY_BREAK case 7:
	  YY_RULE_SETUP
#line 63 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_IMAGES;
	    return IMAGES;
	  }
	YY_BREAK case 8:
	  YY_RULE_SETUP
#line 68 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_FILENAME;
	    return FILENAME;
	  }
	YY_BREAK case 9:
	  YY_RULE_SETUP
#line 73 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_FILEPATH;
	    return FILEPATH;
	  }
	YY_BREAK case 10:
	  YY_RULE_SETUP
#line 78 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_FILESIZE;
	    return FILESIZE;
	  }
	YY_BREAK case 11:
	  YY_RULE_SETUP
#line 83 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_COMMENT;
	    return COMMENT;
	  }
	YY_BREAK case 12:
	  YY_RULE_SETUP
#line 88 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_PAGE_LINK;
	    return PAGE_LINK;
	  }
	YY_BREAK case 13:
	  YY_RULE_SETUP
#line 93 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_PAGE_IDX;
	    return PAGE_IDX;
	  }
	YY_BREAK case 14:
	  YY_RULE_SETUP
#line 98 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_PAGES;
	    return PAGES;
	  }
	YY_BREAK case 15:
	  YY_RULE_SETUP
#line 103 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_TABLE;
	    return TABLE;
	  }
	YY_BREAK case 16:
	  YY_RULE_SETUP
#line 108 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_DATE;
	    return DATE;
	  }
	YY_BREAK case 17:
	  YY_RULE_SETUP
#line 113 "albumtheme.l"
	  {
	    BEGIN (STAG);
	    yylval.ivalue = GTH_TAG_TEXT;
	    return TEXT;
	  }
	YY_BREAK case 18:
	  YY_RULE_SETUP
#line 118 "albumtheme.l"
	  {
	    BEGIN (INITIAL);
	    return TEXT_END;
	  }
	YY_BREAK case 19:
	  YY_RULE_SETUP
#line 122 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_EXPOSURE_TIME;
	    return EXIF_EXPOSURE_TIME;
	  }
	YY_BREAK case 20:
	  YY_RULE_SETUP
#line 127 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_EXPOSURE_MODE;
	    return EXIF_EXPOSURE_MODE;
	  }
	YY_BREAK case 21:
	  YY_RULE_SETUP
#line 132 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_FLASH;
	    return EXIF_FLASH;
	  }
	YY_BREAK case 22:
	  YY_RULE_SETUP
#line 137 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_SHUTTER_SPEED;
	    return EXIF_SHUTTER_SPEED;
	  }
	YY_BREAK case 23:
	  YY_RULE_SETUP
#line 142 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_APERTURE_VALUE;
	    return EXIF_APERTURE_VALUE;
	  }
	YY_BREAK case 24:
	  YY_RULE_SETUP
#line 147 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_FOCAL_LENGTH;
	    return EXIF_FOCAL_LENGTH;
	  }
	YY_BREAK case 25:
	  YY_RULE_SETUP
#line 152 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_DATE_TIME;
	    return EXIF_DATE_TIME;
	  }
	YY_BREAK case 26:
	  YY_RULE_SETUP
#line 157 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EXIF_CAMERA_MODEL;
	    return EXIF_CAMERA_MODEL;
	  }
	YY_BREAK case 27:
	  YY_RULE_SETUP
#line 162 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_SET_VAR;
	    return SET_VAR;
	  }
	YY_BREAK case 28:
	  YY_RULE_SETUP
#line 167 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    yylval.ivalue = GTH_TAG_EVAL;
	    return EVAL;
	  }
	YY_BREAK case 29:
	  YY_RULE_SETUP
#line 172 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return IF;
	  }
	YY_BREAK case 30:
	  YY_RULE_SETUP
#line 176 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return ELSE;
	  }
	YY_BREAK case 31:
	  YY_RULE_SETUP
#line 180 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return ELSE_IF;
	  }
	YY_BREAK case 32:
	  YY_RULE_SETUP
#line 184 "albumtheme.l"
	  {
	    BEGIN (TAG);
	    return END;
	  }
	YY_BREAK case 33:
	  YY_RULE_SETUP
#line 188 "albumtheme.l"
	  {
	    yylval.ivalue = atoi (yytext);
	    return NUMBER;
	  }
	YY_BREAK case 34:
	  YY_RULE_SETUP
#line 192 "albumtheme.l"
	  {
	    yylval.text = g_strdup (yytext);
	    return NAME;
	  }
	YY_BREAK case 35:
	  YY_RULE_SETUP
#line 196 "albumtheme.l"
	  {
	    return '=';
	  }
	YY_BREAK case 36:
	  YY_RULE_SETUP
#line 199 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_LT;
	    return COMPARE;
	  }
	YY_BREAK case 37:
	  YY_RULE_SETUP
#line 203 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_GT;
	    return COMPARE;
	  }
	YY_BREAK case 38:
	  YY_RULE_SETUP
#line 207 "albumtheme.l"
	  {
	    BEGIN (INITIAL);
	    return END_TAG;
	  }
	YY_BREAK case 39:
	  YY_RULE_SETUP
#line 211 "albumtheme.l"
	  {
	    return '+';
	  }
	YY_BREAK case 40:
	  YY_RULE_SETUP
#line 214 "albumtheme.l"
	  {
	    return '-';
	  }
	YY_BREAK case 41:
	  YY_RULE_SETUP
#line 217 "albumtheme.l"
	  {
	    return '*';
	  }
	YY_BREAK case 42:
	  YY_RULE_SETUP
#line 220 "albumtheme.l"
	  {
	    return '/';
	  }
	YY_BREAK case 43:
	  YY_RULE_SETUP
#line 223 "albumtheme.l"
	  {
	    return '!';
	  }
	YY_BREAK case 44:
	  YY_RULE_SETUP
#line 226 "albumtheme.l"
	  {
	    return '(';
	  }
	YY_BREAK case 45:
	  YY_RULE_SETUP
#line 229 "albumtheme.l"
	  {
	    return ')';
	  }
	YY_BREAK case 46:
	  YY_RULE_SETUP
#line 232 "albumtheme.l"
	  {
	    return '"';
	  }
	YY_BREAK case 47:
	  YY_RULE_SETUP
#line 235 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_AND;
	    return BOOL_OP;
	  }
	YY_BREAK case 48:
	  YY_RULE_SETUP
#line 239 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_OR;
	    return BOOL_OP;
	  }
	YY_BREAK case 49:
	  YY_RULE_SETUP
#line 243 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_EQ;
	    return COMPARE;
	  }
	YY_BREAK case 50:
	  YY_RULE_SETUP
#line 247 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_NE;
	    return COMPARE;
	  }
	YY_BREAK case 51:
	  YY_RULE_SETUP
#line 251 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_LE;
	    return COMPARE;
	  }
	YY_BREAK case 52:
	  YY_RULE_SETUP
#line 255 "albumtheme.l"
	  {
	    yylval.ivalue = GTH_OP_CMP_GE;
	    return COMPARE;
	  }
	YY_BREAK case 53:
	  YY_RULE_SETUP
#line 259 "albumtheme.l"
	  {
	    /* Eat spaces inside tag. */
	  }
	YY_BREAK case 54:
	  YY_RULE_SETUP
#line 262 "albumtheme.l"
	  {
	    BEGIN (INITIAL);
	    return END_TAG;
	  }
	YY_BREAK case 55:
	  YY_RULE_SETUP
#line 266 "albumtheme.l"
	  {
	    yylval.text = g_strdup (yytext);
	    return HTML;
	  }
	YY_BREAK case 56:
	  YY_RULE_SETUP
#line 270 "albumtheme.l"
	  {
	    yylval.text = g_strdup (yytext);
	    return HTML;
	  }
	YY_BREAK case YY_STATE_EOF (INITIAL):
	case YY_STATE_EOF (TAG):
	case YY_STATE_EOF (STAG):
#line 274 "albumtheme.l"
	  {
	    return 0;
	  }
	YY_BREAK case 57:
	  YY_RULE_SETUP
#line 278 "albumtheme.l"
	    ECHO;
	  YY_BREAK
#line 1348 "lex.yy.c"
	case YY_END_OF_BUFFER:
	  {
	    /* Amount of text matched not including the EOB char. */
	    int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

	    /* Undo the effects of YY_DO_BEFORE_ACTION. */
	    *yy_cp = yy_hold_char;
	    YY_RESTORE_YY_MORE_OFFSET
	      if (yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW)
	      {
		/* We're scanning a new file or input source.  It's
		 * possible that this happened because the user
		 * just pointed yyin at a new source and called
		 * yylex().  If so, then we have to assure
		 * consistency between yy_current_buffer and our
		 * globals.  Here is the right place to do so, because
		 * this is the first action (other than possibly a
		 * back-up) that will match for the new input source.
		 */
		yy_n_chars = yy_current_buffer->yy_n_chars;
		yy_current_buffer->yy_input_file = yyin;
		yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
	      }

	    /* Note that here we test for yy_c_buf_p "<=" to the position
	     * of the first EOB in the buffer, since yy_c_buf_p will
	     * already have been incremented past the NUL character
	     * (since all states make transitions on EOB to the
	     * end-of-buffer state).  Contrast this with the test
	     * in input().
	     */
	    if (yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars])
	      {			/* This was really a NUL. */
		yy_state_type yy_next_state;

		yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

		yy_current_state = yy_get_previous_state ();

		/* Okay, we're now positioned to make the NUL
		 * transition.  We couldn't have
		 * yy_get_previous_state() go ahead and do it
		 * for us because it doesn't know how to deal
		 * with the possibility of jamming (and we don't
		 * want to build jamming into it because then it
		 * will run more slowly).
		 */

		yy_next_state = yy_try_NUL_trans (yy_current_state);

		yy_bp = yytext_ptr + YY_MORE_ADJ;

		if (yy_next_state)
		  {
		    /* Consume the NUL. */
		    yy_cp = ++yy_c_buf_p;
		    yy_current_state = yy_next_state;
		    goto yy_match;
		  }

		else
		  {
		    yy_cp = yy_c_buf_p;
		    goto yy_find_action;
		  }
	      }

	    else
	      switch (yy_get_next_buffer ())
		{
		case EOB_ACT_END_OF_FILE:
		  {
		    yy_did_buffer_switch_on_eof = 0;

		    if (yywrap ())
		      {
			/* Note: because we've taken care in
			 * yy_get_next_buffer() to have set up
			 * yytext, we can now set up
			 * yy_c_buf_p so that if some total
			 * hoser (like flex itself) wants to
			 * call the scanner after we return the
			 * YY_NULL, it'll still work - another
			 * YY_NULL will get returned.
			 */
			yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

			yy_act = YY_STATE_EOF (YY_START);
			goto do_action;
		      }

		    else
		      {
			if (!yy_did_buffer_switch_on_eof)
			  YY_NEW_FILE;
		      }
		    break;
		  }

		case EOB_ACT_CONTINUE_SCAN:
		  yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

		  yy_current_state = yy_get_previous_state ();

		  yy_cp = yy_c_buf_p;
		  yy_bp = yytext_ptr + YY_MORE_ADJ;
		  goto yy_match;

		case EOB_ACT_LAST_MATCH:
		  yy_c_buf_p = &yy_current_buffer->yy_ch_buf[yy_n_chars];

		  yy_current_state = yy_get_previous_state ();

		  yy_cp = yy_c_buf_p;
		  yy_bp = yytext_ptr + YY_MORE_ADJ;
		  goto yy_find_action;
		}
	    break;
	  }

	default:
	  YY_FATAL_ERROR
	    ("fatal flex scanner internal error--no action found");
	}			/* end of action switch */
    }				/* end of scanning one token */
}				/* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int
yy_get_next_buffer ()
{
  register char *dest = yy_current_buffer->yy_ch_buf;
  register char *source = yytext_ptr;
  register int number_to_move, i;
  int ret_val;

  if (yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1])
    YY_FATAL_ERROR
      ("fatal flex scanner internal error--end of buffer missed");

  if (yy_current_buffer->yy_fill_buffer == 0)
    {				/* Don't try to fill the buffer, so this is an EOF. */
      if (yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1)
	{
	  /* We matched a single character, the EOB, so
	   * treat this as a final EOF.
	   */
	  return EOB_ACT_END_OF_FILE;
	}

      else
	{
	  /* We matched some text prior to the EOB, first
	   * process it.
	   */
	  return EOB_ACT_LAST_MATCH;
	}
    }

  /* Try to read more data. */

  /* First move last chars to start of buffer. */
  number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

  for (i = 0; i < number_to_move; ++i)
    *(dest++) = *(source++);

  if (yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING)
    /* don't do the read, it's not guaranteed to return an EOF,
     * just force an EOF
     */
    yy_current_buffer->yy_n_chars = yy_n_chars = 0;

  else
    {
      int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

      while (num_to_read <= 0)
	{			/* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
	  YY_FATAL_ERROR
	    ("input buffer overflow, can't enlarge buffer because scanner uses REJECT");
#else

	  /* just a shorter name for the current buffer */
	  YY_BUFFER_STATE b = yy_current_buffer;

	  int yy_c_buf_p_offset = (int) (yy_c_buf_p - b->yy_ch_buf);

	  if (b->yy_is_our_buffer)
	    {
	      int new_size = b->yy_buf_size * 2;

	      if (new_size <= 0)
		b->yy_buf_size += b->yy_buf_size / 8;
	      else
		b->yy_buf_size *= 2;

	      b->yy_ch_buf = (char *)
		/* Include room in for 2 EOB chars. */
		yy_flex_realloc ((void *) b->yy_ch_buf, b->yy_buf_size + 2);
	    }
	  else
	    /* Can't grow it, we don't own it. */
	    b->yy_ch_buf = 0;

	  if (!b->yy_ch_buf)
	    YY_FATAL_ERROR ("fatal error - scanner input buffer overflow");

	  yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

	  num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;
#endif
	}

      if (num_to_read > YY_READ_BUF_SIZE)
	num_to_read = YY_READ_BUF_SIZE;

      /* Read in more data. */
      YY_INPUT ((&yy_current_buffer->yy_ch_buf[number_to_move]),
		yy_n_chars, num_to_read);

      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  if (yy_n_chars == 0)
    {
      if (number_to_move == YY_MORE_ADJ)
	{
	  ret_val = EOB_ACT_END_OF_FILE;
	  yyrestart (yyin);
	}

      else
	{
	  ret_val = EOB_ACT_LAST_MATCH;
	  yy_current_buffer->yy_buffer_status = YY_BUFFER_EOF_PENDING;
	}
    }

  else
    ret_val = EOB_ACT_CONTINUE_SCAN;

  yy_n_chars += number_to_move;
  yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
  yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

  yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

  return ret_val;
}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type
yy_get_previous_state ()
{
  register yy_state_type yy_current_state;
  register char *yy_cp;

  yy_current_state = yy_start;

  for (yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp)
    {
      register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI (*yy_cp)] : 1);
      if (yy_accept[yy_current_state])
	{
	  yy_last_accepting_state = yy_current_state;
	  yy_last_accepting_cpos = yy_cp;
	}
      while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
	{
	  yy_current_state = (int) yy_def[yy_current_state];
	  if (yy_current_state >= 340)
	    yy_c = yy_meta[(unsigned int) yy_c];
	}
      yy_current_state =
	yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
    }

  return yy_current_state;
}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type
yy_try_NUL_trans (yy_state_type yy_current_state)
#else
static yy_state_type
yy_try_NUL_trans (yy_current_state)
     yy_state_type yy_current_state;
#endif
{
  register int yy_is_jam;
  register char *yy_cp = yy_c_buf_p;

  register YY_CHAR yy_c = 1;
  if (yy_accept[yy_current_state])
    {
      yy_last_accepting_state = yy_current_state;
      yy_last_accepting_cpos = yy_cp;
    }
  while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
      yy_current_state = (int) yy_def[yy_current_state];
      if (yy_current_state >= 340)
	yy_c = yy_meta[(unsigned int) yy_c];
    }
  yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
  yy_is_jam = (yy_current_state == 339);

  return yy_is_jam ? 0 : yy_current_state;
}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void
yyunput (int c, register char *yy_bp)
#else
static void
yyunput (c, yy_bp)
     int c;
     register char *yy_bp;
#endif
{
  register char *yy_cp = yy_c_buf_p;

  /* undo effects of setting up yytext */
  *yy_cp = yy_hold_char;

  if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
    {				/* need to shift things up to make room */
      /* +2 for EOB chars. */
      register int number_to_move = yy_n_chars + 2;
      register char *dest =
	&yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
      register char *source = &yy_current_buffer->yy_ch_buf[number_to_move];

      while (source > yy_current_buffer->yy_ch_buf)
	*--dest = *--source;

      yy_cp += (int) (dest - source);
      yy_bp += (int) (dest - source);
      yy_current_buffer->yy_n_chars =
	yy_n_chars = yy_current_buffer->yy_buf_size;

      if (yy_cp < yy_current_buffer->yy_ch_buf + 2)
	YY_FATAL_ERROR ("flex scanner push-back overflow");
    }

  *--yy_cp = (char) c;


  yytext_ptr = yy_bp;
  yy_hold_char = *yy_cp;
  yy_c_buf_p = yy_cp;
}
#endif /* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int
yyinput ()
#else
static int
input ()
#endif
{
  int c;

  *yy_c_buf_p = yy_hold_char;

  if (*yy_c_buf_p == YY_END_OF_BUFFER_CHAR)
    {
      /* yy_c_buf_p now points to the character we want to return.
       * If this occurs *before* the EOB characters, then it's a
       * valid NUL; if not, then we've hit the end of the buffer.
       */
      if (yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars])
	/* This was really a NUL. */
	*yy_c_buf_p = '\0';

      else
	{			/* need more input */
	  int offset = yy_c_buf_p - yytext_ptr;
	  ++yy_c_buf_p;

	  switch (yy_get_next_buffer ())
	    {
	    case EOB_ACT_LAST_MATCH:
	      /* This happens because yy_g_n_b()
	       * sees that we've accumulated a
	       * token and flags that we need to
	       * try matching the token before
	       * proceeding.  But for input(),
	       * there's no matching to consider.
	       * So convert the EOB_ACT_LAST_MATCH
	       * to EOB_ACT_END_OF_FILE.
	       */

	      /* Reset buffer status. */
	      yyrestart (yyin);

	      /* fall through */

	    case EOB_ACT_END_OF_FILE:
	      {
		if (yywrap ())
		  return EOF;

		if (!yy_did_buffer_switch_on_eof)
		  YY_NEW_FILE;
#ifdef __cplusplus
		return yyinput ();
#else
		return input ();
#endif
	      }

	    case EOB_ACT_CONTINUE_SCAN:
	      yy_c_buf_p = yytext_ptr + offset;
	      break;
	    }
	}
    }

  c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
  *yy_c_buf_p = '\0';		/* preserve yytext */
  yy_hold_char = *++yy_c_buf_p;


  return c;
}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void
yyrestart (FILE * input_file)
#else
void
yyrestart (input_file)
     FILE *input_file;
#endif
{
  if (!yy_current_buffer)
    yy_current_buffer = yy_create_buffer (yyin, YY_BUF_SIZE);

  yy_init_buffer (yy_current_buffer, input_file);
  yy_load_buffer_state ();
}


#ifdef YY_USE_PROTOS
void
yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
#else
void
yy_switch_to_buffer (new_buffer)
     YY_BUFFER_STATE new_buffer;
#endif
{
  if (yy_current_buffer == new_buffer)
    return;

  if (yy_current_buffer)
    {
      /* Flush out information for old buffer. */
      *yy_c_buf_p = yy_hold_char;
      yy_current_buffer->yy_buf_pos = yy_c_buf_p;
      yy_current_buffer->yy_n_chars = yy_n_chars;
    }

  yy_current_buffer = new_buffer;
  yy_load_buffer_state ();

  /* We don't actually know whether we did this switch during
   * EOF (yywrap()) processing, but the only time this flag
   * is looked at is after yywrap() is called, so it's safe
   * to go ahead and always set it.
   */
  yy_did_buffer_switch_on_eof = 1;
}


#ifdef YY_USE_PROTOS
void
yy_load_buffer_state (void)
#else
void
yy_load_buffer_state ()
#endif
{
  yy_n_chars = yy_current_buffer->yy_n_chars;
  yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
  yyin = yy_current_buffer->yy_input_file;
  yy_hold_char = *yy_c_buf_p;
}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_create_buffer (FILE * file, int size)
#else
YY_BUFFER_STATE
yy_create_buffer (file, size)
     FILE *file;
     int size;
#endif
{
  YY_BUFFER_STATE b;

  b = (YY_BUFFER_STATE) yy_flex_alloc (sizeof (struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR ("out of dynamic memory in yy_create_buffer()");

  b->yy_buf_size = size;

  /* yy_ch_buf has to be 2 characters longer than the size given because
   * we need to put in 2 end-of-buffer characters.
   */
  b->yy_ch_buf = (char *) yy_flex_alloc (b->yy_buf_size + 2);
  if (!b->yy_ch_buf)
    YY_FATAL_ERROR ("out of dynamic memory in yy_create_buffer()");

  b->yy_is_our_buffer = 1;

  yy_init_buffer (b, file);

  return b;
}


#ifdef YY_USE_PROTOS
void
yy_delete_buffer (YY_BUFFER_STATE b)
#else
void
yy_delete_buffer (b)
     YY_BUFFER_STATE b;
#endif
{
  if (!b)
    return;

  if (b == yy_current_buffer)
    yy_current_buffer = (YY_BUFFER_STATE) 0;

  if (b->yy_is_our_buffer)
    yy_flex_free ((void *) b->yy_ch_buf);

  yy_flex_free ((void *) b);
}



#ifdef YY_USE_PROTOS
void
yy_init_buffer (YY_BUFFER_STATE b, FILE * file)
#else
void
yy_init_buffer (b, file)
     YY_BUFFER_STATE b;
     FILE *file;
#endif


{
  yy_flush_buffer (b);

  b->yy_input_file = file;
  b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
  b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
  b->yy_is_interactive = 0;
#else
  b->yy_is_interactive = file ? (isatty (fileno (file)) > 0) : 0;
#endif
#endif
}


#ifdef YY_USE_PROTOS
void
yy_flush_buffer (YY_BUFFER_STATE b)
#else
void
yy_flush_buffer (b)
     YY_BUFFER_STATE b;
#endif

{
  if (!b)
    return;

  b->yy_n_chars = 0;

  /* We always need two end-of-buffer characters.  The first causes
   * a transition to the end-of-buffer state.  The second causes
   * a jam in that state.
   */
  b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
  b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

  b->yy_buf_pos = &b->yy_ch_buf[0];

  b->yy_at_bol = 1;
  b->yy_buffer_status = YY_BUFFER_NEW;

  if (b == yy_current_buffer)
    yy_load_buffer_state ();
}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_buffer (char *base, yy_size_t size)
#else
YY_BUFFER_STATE
yy_scan_buffer (base, size)
     char *base;
     yy_size_t size;
#endif
{
  YY_BUFFER_STATE b;

  if (size < 2 ||
      base[size - 2] != YY_END_OF_BUFFER_CHAR ||
      base[size - 1] != YY_END_OF_BUFFER_CHAR)
    /* They forgot to leave room for the EOB's. */
    return 0;

  b = (YY_BUFFER_STATE) yy_flex_alloc (sizeof (struct yy_buffer_state));
  if (!b)
    YY_FATAL_ERROR ("out of dynamic memory in yy_scan_buffer()");

  b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
  b->yy_buf_pos = b->yy_ch_buf = base;
  b->yy_is_our_buffer = 0;
  b->yy_input_file = 0;
  b->yy_n_chars = b->yy_buf_size;
  b->yy_is_interactive = 0;
  b->yy_at_bol = 1;
  b->yy_fill_buffer = 0;
  b->yy_buffer_status = YY_BUFFER_NEW;

  yy_switch_to_buffer (b);

  return b;
}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_string (yyconst char *yy_str)
#else
YY_BUFFER_STATE
yy_scan_string (yy_str)
     yyconst char *yy_str;
#endif
{
  int len;
  for (len = 0; yy_str[len]; ++len)
    ;

  return yy_scan_bytes (yy_str, len);
}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE
yy_scan_bytes (yyconst char *bytes, int len)
#else
YY_BUFFER_STATE
yy_scan_bytes (bytes, len)
     yyconst char *bytes;
     int len;
#endif
{
  YY_BUFFER_STATE b;
  char *buf;
  yy_size_t n;
  int i;

  /* Get memory for full buffer, including space for trailing EOB's. */
  n = len + 2;
  buf = (char *) yy_flex_alloc (n);
  if (!buf)
    YY_FATAL_ERROR ("out of dynamic memory in yy_scan_bytes()");

  for (i = 0; i < len; ++i)
    buf[i] = bytes[i];

  buf[len] = buf[len + 1] = YY_END_OF_BUFFER_CHAR;

  b = yy_scan_buffer (buf, n);
  if (!b)
    YY_FATAL_ERROR ("bad buffer in yy_scan_bytes()");

  /* It's okay to grow etc. this buffer, and we should throw it
   * away when we're done.
   */
  b->yy_is_our_buffer = 1;

  return b;
}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void
yy_push_state (int new_state)
#else
static void
yy_push_state (new_state)
     int new_state;
#endif
{
  if (yy_start_stack_ptr >= yy_start_stack_depth)
    {
      yy_size_t new_size;

      yy_start_stack_depth += YY_START_STACK_INCR;
      new_size = yy_start_stack_depth * sizeof (int);

      if (!yy_start_stack)
	yy_start_stack = (int *) yy_flex_alloc (new_size);

      else
	yy_start_stack = (int *) yy_flex_realloc ((void *) yy_start_stack,
						  new_size);

      if (!yy_start_stack)
	YY_FATAL_ERROR ("out of memory expanding start-condition stack");
    }

  yy_start_stack[yy_start_stack_ptr++] = YY_START;

  BEGIN (new_state);
}
#endif


#ifndef YY_NO_POP_STATE
static void
yy_pop_state ()
{
  if (--yy_start_stack_ptr < 0)
    YY_FATAL_ERROR ("start-condition stack underflow");

  BEGIN (yy_start_stack[yy_start_stack_ptr]);
}
#endif


#ifndef YY_NO_TOP_STATE
static int
yy_top_state ()
{
  return yy_start_stack[yy_start_stack_ptr - 1];
}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void
yy_fatal_error (yyconst char msg[])
#else
static void
yy_fatal_error (msg)
     char msg[];
#endif
{
  (void) fprintf (stderr, "%s\n", msg);
  exit (YY_EXIT_FAILURE);
}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void
yy_flex_strncpy (char *s1, yyconst char *s2, int n)
#else
static void
yy_flex_strncpy (s1, s2, n)
     char *s1;
     yyconst char *s2;
     int n;
#endif
{
  register int i;
  for (i = 0; i < n; ++i)
    s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int
yy_flex_strlen (yyconst char *s)
#else
static int
yy_flex_strlen (s)
     yyconst char *s;
#endif
{
  register int n;
  for (n = 0; s[n]; ++n)
    ;

  return n;
}
#endif


#ifdef YY_USE_PROTOS
static void *
yy_flex_alloc (yy_size_t size)
#else
static void *
yy_flex_alloc (size)
     yy_size_t size;
#endif
{
  return (void *) malloc (size);
}

#ifdef YY_USE_PROTOS
static void *
yy_flex_realloc (void *ptr, yy_size_t size)
#else
static void *
yy_flex_realloc (ptr, size)
     void *ptr;
     yy_size_t size;
#endif
{
  /* The cast to (char *) in the following accommodates both
   * implementations that use char* generic pointers, and those
   * that use void* generic pointers.  It works with the latter
   * because both ANSI C and C++ allow castless assignment from
   * any pointer type to void*, and deal with argument conversions
   * as though doing an assignment.
   */
  return (void *) realloc ((char *) ptr, size);
}

#ifdef YY_USE_PROTOS
static void
yy_flex_free (void *ptr)
#else
static void
yy_flex_free (ptr)
     void *ptr;
#endif
{
  free (ptr);
}

#if YY_MAIN
int
main ()
{
  yylex ();
  return 0;
}
#endif
#line 278 "albumtheme.l"
